'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { api } from '@/lib/api/client';
import type { Order } from '@/lib/api/orders.api';
const statuses = ['CONFIRMED', 'PROCESSING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED'];
export default function AdminOrderDetailsPage() { const params = useParams<{ id: string }>(); const [order, setOrder] = useState<Order | null>(null); const [status, setStatus] = useState(''); const [error, setError] = useState(''); useEffect(() => { api.get<Order>(`/admin/orders/${params.id}`).then((x) => { setOrder(x); setStatus(x.status); }).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load order.')); }, [params.id]); if (!order) return <main className="p-6">{error || 'Loading order…'}</main>; return <main className="mx-auto max-w-5xl space-y-6 p-6"><Link href="/admin/orders" className="text-sm underline">← Admin orders</Link><div className="flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-bold">{order.orderNumber}</h1><span>{order.status}</span></div>{error && <p role="alert" className="rounded border border-red-400 p-3 text-red-500">{error}</p>}<section className="rounded-lg border p-5"><h2 className="font-semibold">Update status</h2><div className="mt-3 flex gap-3"><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded border bg-background p-2">{statuses.map((item) => <option key={item}>{item}</option>)}</select><button className="rounded bg-primary px-4 py-2 text-primary-foreground" onClick={async () => { try { const updated = await api.patch<Order>(`/admin/orders/${order.id}/status`, { status }); setOrder({ ...order, ...updated }); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update status.'); } }}>Save</button></div></section><section className="rounded-lg border p-5"><h2 className="font-semibold">Items</h2>{order.items.map((item) => <p key={item.id} className="border-b py-2">{item.productNameSnapshot} × {item.quantity} — {order.currency} {item.lineTotal}</p>)}</section><section className="rounded-lg border p-5"><h2 className="font-semibold">Add shipment</h2><ShipmentForm orderId={order.id} onDone={(shipment) => setOrder({ ...order, shipments: [shipment, ...order.shipments] })} /></section></main>; }
function ShipmentForm({ orderId, onDone }: { orderId: string; onDone: (shipment: Order['shipments'][number]) => void }) { const [carrier, setCarrier] = useState(''); const [trackingNumber, setTrackingNumber] = useState(''); const [trackingUrl, setTrackingUrl] = useState(''); return <div className="mt-3 grid gap-2 md:grid-cols-4"><input className="rounded border bg-background p-2" placeholder="Carrier" value={carrier} onChange={(e) => setCarrier(e.target.value)} /><input className="rounded border bg-background p-2" placeholder="Tracking number" value={trackingNumber} onChange={(e) => setTrackingNumber(e.target.value)} /><input className="rounded border bg-background p-2" placeholder="Tracking URL" value={trackingUrl} onChange={(e) => setTrackingUrl(e.target.value)} /><button className="rounded border px-3 py-2" onClick={async () => { const shipment = await api.post<Order['shipments'][number]>(`/admin/orders/${orderId}/shipment`, { carrier, trackingNumber, trackingUrl, status: 'SHIPPED' }); onDone(shipment); }}>Create shipment</button></div>; }
