'use client';
import { useEffect, useState } from 'react';
import { reviewsApi, Review } from '@/lib/api/reviews.api';
import { RatingStars } from './rating-stars';

export function ReviewSection({ productId }: { productId: string }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [rating, setRating] = useState(0); const [title, setTitle] = useState(''); const [comment, setComment] = useState(''); const [orderId, setOrderId] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { reviewsApi.list(productId).then(setReviews).catch(() => setError('Reviews could not be loaded.')).finally(() => setLoading(false)); }, [productId]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const review = await reviewsApi.create(productId, { orderId, rating, title, comment }); setReviews((items) => [review, ...items]); setTitle(''); setComment(''); setOrderId(''); setRating(0); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to submit review.'); } finally { setSaving(false); } }
  return <section className="mt-12 grid gap-8 lg:grid-cols-[1fr_360px]"><div><h2 className="text-2xl font-semibold">Customer reviews</h2>{loading ? <p className="mt-4 text-muted-foreground">Loading reviews…</p> : reviews.length ? <div className="mt-5 space-y-4">{reviews.map((review) => <article key={review.id} className="rounded-xl border p-5"><div className="flex items-center justify-between gap-4"><RatingStars value={review.rating} readOnly /><span className="text-xs text-muted-foreground">Verified buyer</span></div><h3 className="mt-2 font-semibold">{review.title}</h3><p className="mt-1 text-sm text-muted-foreground">{review.comment}</p></article>)}</div> : <div className="mt-4 rounded-xl border border-dashed p-8 text-center text-muted-foreground">No reviews yet. Be the first to share your experience.</div>}</div><form onSubmit={submit} className="rounded-xl border p-5"><h3 className="font-semibold">Write a review</h3><p className="mt-1 text-xs text-muted-foreground">Reviews are published after moderation.</p>{error && <p role="alert" className="mt-3 rounded border border-red-300 p-2 text-sm text-red-600">{error}</p>}<label className="mt-4 block text-sm font-medium">Order ID<input required value={orderId} onChange={(e) => setOrderId(e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2" placeholder="Your completed order ID" /></label><div className="mt-4"><span className="text-sm font-medium">Rating</span><RatingStars value={rating} onChange={setRating} /></div><input required value={title} onChange={(e) => setTitle(e.target.value)} className="mt-4 w-full rounded-md border bg-background p-2" placeholder="Review title" /><textarea required value={comment} onChange={(e) => setComment(e.target.value)} className="mt-3 min-h-28 w-full rounded-md border bg-background p-2" placeholder="Tell us about the product" /><button disabled={saving || rating === 0} className="mt-4 w-full rounded-md bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50">{saving ? 'Submitting…' : 'Submit review'}</button></form></section>;
}
