'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api/client';

type Dashboard = { revenue: string | number; orders: number; averageOrderValue: string | number; customers: number; lowStockProducts: number; bestSellingProducts: Array<{ productId: string; _sum: { quantity: number | null; lineTotal: string | number | null } }>; recentActivities: Array<{ id: string; orderNumber: string; status: string; grandTotal: string | number; createdAt: string; user: { email: string } }> };
export default function AdminDashboardPage() {
  const [data, setData] = useState<Dashboard>(); const [error, setError] = useState('');
  useEffect(() => { api.get<Dashboard>('/admin/dashboard').then(setData).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load dashboard.')); }, []);
  const money = (value: string | number | undefined) => `${Number(value ?? 0).toFixed(2)} USD`;
  return <main className="mx-auto max-w-7xl space-y-8 px-4 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Business overview</p><h1 className="text-3xl font-bold">Admin dashboard</h1><p className="mt-2 text-muted-foreground">Live performance across orders, customers, products, and inventory.</p></div><nav className="flex flex-wrap gap-3 text-sm"><Link className="text-primary underline" href="/admin/analytics">Analytics</Link><Link className="text-primary underline" href="/admin/reports">Reports</Link><Link className="text-primary underline" href="/admin/customers">Customers</Link></nav></div>{error && <p role="alert" className="rounded border border-red-300 p-3 text-red-600">{error}</p>}{!data ? <p className="text-muted-foreground" aria-live="polite">Loading dashboard…</p> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Revenue', money(data.revenue)], ['Orders', data.orders], ['Average order', money(data.averageOrderValue)], ['Customers', data.customers]].map(([label, value]) => <article className="rounded-2xl border bg-card p-5" key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p></article>)}</div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent activity</h2><Link href="/admin/orders" className="text-sm text-primary underline">View orders</Link></div><div className="mt-4 divide-y">{data.recentActivities.length ? data.recentActivities.map((item) => <div className="flex flex-wrap justify-between gap-3 py-3 text-sm" key={item.id}><div><p className="font-medium">{item.orderNumber}</p><p className="text-muted-foreground">{item.user.email} · {item.status}</p></div><span>{money(item.grandTotal)}</span></div>) : <p className="py-6 text-muted-foreground">No recent activity.</p>}</div></section><section className="rounded-2xl border p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Inventory alert</h2><Link href="/admin/analytics" className="text-sm text-primary underline">Inspect analytics</Link></div><p className="mt-4 text-3xl font-bold">{data.lowStockProducts}</p><p className="text-sm text-muted-foreground">variants at or below the reorder threshold</p></section></div></>}</main>;
}
