import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
import { PrismaService } from '../../database/prisma.service';
import { QUEUES } from '../../queue/queue.constants';
@Injectable()
export class InventoryService {
  constructor(private readonly prisma:PrismaService,@InjectQueue(QUEUES.INVENTORY) private readonly inventoryQueue:Queue){}
  async availability(variantId:string){const levels=await this.prisma.inventoryLevel.findMany({where:{productVariantId:variantId,warehouse:{status:'ACTIVE'}},include:{warehouse:true}});if(!levels.length)throw new NotFoundException('Inventory not found');return {variantId,available:levels.reduce((n,l)=>n+l.quantityAvailable,0),reserved:levels.reduce((n,l)=>n+l.quantityReserved,0),sellable:levels.reduce((n,l)=>n+Math.max(0,l.quantityAvailable-l.quantityReserved),0),warehouses:levels};}
  async list(){return this.prisma.inventoryLevel.findMany({include:{warehouse:true,variant:{include:{product:true}}},orderBy:{updatedAt:'desc'}});}
  async lowStock(){return this.prisma.inventoryLevel.findMany({where:{quantityAvailable:{lte:0}},include:{warehouse:true,variant:{include:{product:true}}}});}
  async movements(){return this.prisma.inventoryMovement.findMany({include:{warehouse:true,variant:{include:{product:true}},actor:true},orderBy:{createdAt:'desc'}});}
  async warehouses(){return this.prisma.warehouse.findMany({orderBy:{createdAt:'desc'}});}
  async warehouse(id:string){const item=await this.prisma.warehouse.findUnique({where:{id},include:{levels:true}});if(!item)throw new NotFoundException('Warehouse not found');return item;}
  async createWarehouse(data:{name:string;code:string;address?:string;city?:string;province?:string;country?:string}){if(!data.name?.trim()||!data.code?.trim())throw new BadRequestException('Warehouse name and code are required');return this.prisma.warehouse.create({data:{...data,name:data.name.trim(),code:data.code.trim().toUpperCase()}});}
  async updateWarehouse(id:string,data:Record<string,unknown>){await this.warehouse(id);return this.prisma.warehouse.update({where:{id},data});}
  async deleteWarehouse(id:string){await this.warehouse(id);return this.prisma.warehouse.update({where:{id},data:{status:'INACTIVE'}});}
  async reserve(cartId:string, productVariantId:string, quantity:number, ttlMinutes=15){if(!cartId||!productVariantId||!Number.isInteger(quantity)||quantity<1)throw new BadRequestException('Invalid reservation');const expiresAt=new Date(Date.now()+Math.max(1,ttlMinutes)*60000);const result=await this.prisma.$transaction(async tx=>{const level=await tx.inventoryLevel.findFirst({where:{productVariantId,warehouse:{status:'ACTIVE'},quantityAvailable:{gte:quantity}}});if(!level)throw new BadRequestException('Insufficient stock');const updated=await tx.inventoryLevel.updateMany({where:{id:level.id,quantityReserved:{lte:level.quantityAvailable-quantity}},data:{quantityReserved:{increment:quantity}}});if(updated.count!==1)throw new BadRequestException('Insufficient stock');const reservation=await tx.stockReservation.create({data:{cartId,warehouseId:level.warehouseId,productVariantId,quantity,expiresAt}});await tx.inventoryMovement.create({data:{warehouseId:level.warehouseId,productVariantId,type:'RESERVATION',quantity,referenceType:'CART',referenceId:cartId,reason:'Stock reserved'}});return reservation;});await this.inventoryQueue.add('release-reservation',{reservationId:result.id},{delay:Math.max(1000,expiresAt.getTime()-Date.now()),jobId:`reservation-${result.id}`,removeOnComplete:true});return result;}
  async reserveCart(cartId:string, ttlMinutes=15){const cart=await this.prisma.cart.findUnique({where:{id:cartId},include:{items:true}});if(!cart)throw new NotFoundException('Cart not found');const reservations=[];for(const item of cart.items){if(!item.variantId)continue;const existing=await this.prisma.stockReservation.findFirst({where:{cartId,productVariantId:item.variantId,status:'ACTIVE',expiresAt:{gt:new Date()}}});if(existing&&existing.quantity>=item.quantity){reservations.push(existing);continue;}if(existing)await this.release(existing.id);reservations.push(await this.reserve(cartId,item.variantId,item.quantity,ttlMinutes));}return {cartId,reservations};}
  async release(reservationId:string){return this.prisma.$transaction(async tx=>{const r=await tx.stockReservation.findUnique({where:{id:reservationId}});if(!r||r.status!=='ACTIVE')throw new NotFoundException('Active reservation not found');await tx.inventoryLevel.update({where:{warehouseId_productVariantId:{warehouseId:r.warehouseId,productVariantId:r.productVariantId}},data:{quantityReserved:{decrement:r.quantity}}});const done=await tx.stockReservation.update({where:{id:r.id},data:{status:'RELEASED',releasedAt:new Date()}});await tx.inventoryMovement.create({data:{warehouseId:r.warehouseId,productVariantId:r.productVariantId,type:'RESERVATION_RELEASE',quantity:r.quantity,referenceType:'CART',referenceId:r.cartId,reason:'Reservation released'}});return done;});}
  async expire(){const rows=await this.prisma.stockReservation.findMany({where:{status:'ACTIVE',expiresAt:{lte:new Date()}}});for(const r of rows){try{await this.release(r.id);}catch{}}return {released:rows.length};}
  async releaseCart(cartId:string){const rows=await this.prisma.stockReservation.findMany({where:{cartId,status:'ACTIVE'}});for(const row of rows){try{await this.release(row.id);}catch{}}return {released:rows.length};}
  async convertCart(cartId:string){const rows=await this.prisma.stockReservation.findMany({where:{cartId,status:'ACTIVE'}});for(const row of rows){await this.prisma.$transaction(async tx=>{await tx.inventoryLevel.update({where:{warehouseId_productVariantId:{warehouseId:row.warehouseId,productVariantId:row.productVariantId}},data:{quantityAvailable:{decrement:row.quantity},quantityReserved:{decrement:row.quantity}}});await tx.stockReservation.update({where:{id:row.id},data:{status:'CONVERTED',convertedAt:new Date()}});await tx.inventoryMovement.create({data:{warehouseId:row.warehouseId,productVariantId:row.productVariantId,type:'STOCK_OUT',quantity:row.quantity,referenceType:'CHECKOUT',referenceId:cartId,reason:'Checkout reservation converted'}});});}return {converted:rows.length};}
  async adjust(warehouseId:string,productVariantId:string,quantity:number,reason?:string,createdBy?:string){if(!Number.isInteger(quantity)||quantity===0)throw new BadRequestException('Invalid adjustment');return this.prisma.$transaction(async tx=>{const level=await tx.inventoryLevel.findUnique({where:{warehouseId_productVariantId:{warehouseId,productVariantId}}});if(!level)throw new NotFoundException('Inventory not found');const next=level.quantityAvailable+quantity;if(next<0)throw new BadRequestException('Adjustment would create negative stock');const updated=await tx.inventoryLevel.update({where:{id:level.id},data:{quantityAvailable:next}});await tx.inventoryMovement.create({data:{warehouseId,productVariantId,type:'ADJUSTMENT',quantity:Math.abs(quantity),reason,createdBy}});return updated;});}
}
